### ISSUE TITLE
Propose main language be english 

### ISSUE THREAD

**Issue by sergiomb2** [QNapi/qnapi#76]
I don't understand polish , neither more than 70% of the world .

**Comment by Fincer** [comment]
I agree. As a temporary solution, you may find this interesting:

https://github.com/Fincer/linux-patches-and-scripts/tree/master/qnapi

**Comment by sergiomb2** [comment]
I will test soon as possible , LGTM

**Comment by Fincer** [comment]
One step further to rewrite some parts of QNapi for multi-language support. Shouldn't be too difficult to do that, is it?

Technically, the program is quite handy, but polish language is a major roadblock for it to spread wider in foreign communities.

Though I wouldn't mind adding support for more subtitle engines than Napisy24, NapiProjekt & OpenSubtitles (YIFY subs anyone?). I understand the two first ones exist there, of course, because the whole program is hardcoded only for polish language so majority of the users are likely poles and these webpages are specifically preferred by the polish people.

**Comment by krzemin** [comment]
English is now supported, set as default if no other translations are available.

**Comment by sergiomb2** [comment]
thanks a lot , I will test it soon .
