### ISSUE TITLE
Autodetect system language 

### ISSUE THREAD

**Issue by goetzc** [QNapi/qnapi#78]
That would be handy for non-polish speaking people. The GUI and command line language.

**Comment by maciex** [comment]
I think autodetection will not be enough.
All messages and UI texts are written in Polish and there's no internationalization implemented. Also there are no translations to other languages.

**Comment by tactidact** [comment]
A translation can easily be accomplished by use of Google Translate, Polish to English is pretty accurate. Its what I use right now, but I'd really appreciate a translation to save me the trouble. Willing to help out and do the labour if needed.

**Comment by Fincer** [comment]
For those looking for english interface for the program, you may find the following interesting for meanwhile:

https://github.com/Fincer/linux-patches-and-scripts/tree/master/qnapi

As the default language is hardcoded to polish and I wanted to fix this issue quickly, I changed all polish strings to their english equivalents and uploaded patch files to Github. The translation is not 100% perfect, some strings may still remain untranslated (something I missed?) but at least the program is now usable for foreign people preferring english language.

However, a long term plan would be to unhardcode the strings so that the program grabs all needed strings from a separate text file (which is made for all supported languages). This approach is pretty common in many multi-lang programs. I hope QNapi will do the same some day.

**Comment by krzemin** [comment]
The program was translated to English (mostly by @Fincer), and there is Polish Qt Linguist translation available, both for GUI and CLI. Auto-detection of system language is implemented as well, so I think we can close this issue.

Feel free to submit PRs with translations to other languages :)
